--CREATE DATABASE CompanyDB;

USE CompanyDB;

CREATE TABLE Employees (
 EmployeeID INT PRIMARY KEY IDENTITY(1,1),
 FirstName NVARCHAR(50) NOT NULL,
 LastName NVARCHAR(50) NOT NULL,
 Email NVARCHAR(100) UNIQUE,
 HireDate DATE DEFAULT GETDATE(),
 Salary DECIMAL(10,2)
);